//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baykan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        public int MerchantId { get; set; }
        public string MerchantUsername { get; set; }
        public string MerchantPassword { get; set; }
    }
}
